export const POWERS = [
  {
    id: "fire",       name: "Bola de fuego",    color: "#ff4500", bg: "rgba(60,15,0,0.95)",
    alpha: 0.68, duration: 2, category: "fuego",
    desc: "Quemadura · 2 turnos",
    detail: "Daño por fuego a cualquier criatura que permanezca en el área.",
    sound: "fire",
  },
  {
    id: "fire_wall",  name: "Muro de fuego",    color: "#c44216", bg: "rgba(40,10,0,0.95)",
    alpha: 0.82, duration: 3, category: "fuego",
    desc: "Barrera ígnea · 3 turnos",
    detail: "Bloquea el paso y causa daño a quien intente cruzar.",
    sound: "fire",
  },
  {
    id: "ice",        name: "Tormenta de hielo", color: "#48cae4", bg: "rgba(0,30,50,0.95)",
    alpha: 0.60, duration: 3, category: "agua",
    desc: "Congela · 3 turnos",
    detail: "Ralentiza y puede congelar criaturas dentro del área.",
    sound: "ice",
  },
  {
    id: "lightning",  name: "Rayo",              color: "#ffe040", bg: "rgba(40,35,0,0.95)",
    alpha: 0.85, duration: 1, category: "aire",
    desc: "Impacto instantáneo",
    detail: "Daño masivo inmediato. Desaparece al instante.",
    sound: "lightning",
  },
  {
    id: "poison",     name: "Nube venenosa",     color: "#9b5de5", bg: "rgba(25,8,45,0.95)",
    alpha: 0.65, duration: 4, category: "naturaleza",
    desc: "Veneno · 4 turnos",
    detail: "Daño por veneno al inicio de cada turno dentro del área.",
    sound: "poison",
  },
  {
    id: "earth",      name: "Muro de tierra",   color: "#c9a84c", bg: "rgba(35,25,0,0.95)",
    alpha: 0.80, duration: 1, category: "tierra",
    desc: "Barrera permanente",
    detail: "Permanente hasta ser destruida. Bloquea el movimiento.",
    sound: "earth",
  },
  {
    id: "holy",       name: "Aura sagrada",     color: "#ffd700", bg: "rgba(40,35,0,0.95)",
    alpha: 0.55, duration: 3, category: "sagrado",
    desc: "Zona bendita · 3 turnos",
    detail: "Daño extra a no-muertos y demonios en el área.",
    sound: "holy",
  },
  {
    id: "darkness",   name: "Oscuridad",        color: "#7c6fff", bg: "rgba(10,8,40,0.95)",
    alpha: 0.78, duration: 2, category: "sombra",
    desc: "Tinieblas · 2 turnos",
    detail: "Impide la visión. Criaturas con visión oscura no se ven afectadas.",
    sound: "darkness",
  },
  {
    id: "water",      name: "Inundación",       color: "#2196f3", bg: "rgba(0,20,50,0.95)",
    alpha: 0.60, duration: 3, category: "agua",
    desc: "Inundado · 3 turnos",
    detail: "Dificulta el movimiento. Criaturas de fuego sufren daño extra.",
    sound: "water",
  },
  {
    id: "wind",       name: "Torbellino",       color: "#80cbc4", bg: "rgba(0,30,28,0.95)",
    alpha: 0.55, duration: 2, category: "aire",
    desc: "Viento · 2 turnos",
    detail: "Empuja criaturas fuera del área al inicio de su turno.",
    sound: "wind",
  },
  {
    id: "acid",       name: "Lluvia ácida",     color: "#a8d000", bg: "rgba(20,28,0,0.95)",
    alpha: 0.68, duration: 3, category: "naturaleza",
    desc: "Ácido · 3 turnos",
    detail: "Daño por ácido y degrada equipo metálico.",
    sound: "poison",
  },
  {
    id: "necrotic",   name: "Aura de muerte",   color: "#556b2f", bg: "rgba(8,14,0,0.95)",
    alpha: 0.75, duration: 3, category: "sombra",
    desc: "Necrosis · 3 turnos",
    detail: "Drena vida de criaturas vivas. Fortalece a no-muertos.",
    sound: "darkness",
  },
];

export const CATEGORIES = {
  fuego:      { color: "#ff4500", label: "Fuego"      },
  agua:       { color: "#2196f3", label: "Agua"       },
  aire:       { color: "#ffe040", label: "Aire"       },
  tierra:     { color: "#c9a84c", label: "Tierra"     },
  naturaleza: { color: "#a8d000", label: "Naturaleza" },
  sagrado:    { color: "#ffd700", label: "Sagrado"    },
  sombra:     { color: "#7c6fff", label: "Sombra"     },
};
